name: TubeSync
version: latest
slug: tubesync
description: PVR (personal video recorder) for YouTube
url: https://github.com/jackbeau/hassio-addons
panel_icon: mdi:record-player
startup: application
arch:
  - amd64
  - aarch64
  - amd64
ports:
  4848/tcp: 4848
ports_description:
  4848/tcp: TubeSync UI
image: ghcr.io/meeb/tubesync
map:
  - type: media
    read_only: False
    path:  /downloads
  - type: addon_config
    read_only: False
    path: /config
environment:
  TZ: Europe/London
  PUID: "1000"
  PGID: "1000"
init: false