name: TubeSync
version: dev
slug: tubesync
description: PVR (personal video recorder) for YouTube
url: https://github.com/jackbeau/hassio-addons
ingress: true
ingress_stream: true
panel_icon: mdi:apple
startup: application
arch:
  - armv7
  - aarch64
  - amd64
ports:
  8581/tcp: 8581
ports_description:
  8581/tcp: Homebridge UI
host_network: true
init: false
map:
  - addon_config:rw